server:
  port: ${PORT:50101}
spring:
  application:
    name: bwqc-govern-center
eureka:
  client:
    register-with-eureka: true #服务注册是否将自己注册到Eurake服务中
    fetch-registry: true  #服务发现是否从eurake中获取注册信息
    service-url: #Eurake客户端与Eurake服务端交互地址，高可用状态下配置对方的地址，单机状态下配置自己
      defaultZone: ${EURAKE_SERVER:http://eureke02:50102/eureke/}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 6000 #服务注册列表清理时间
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01}
