server:
  port: 31000
spring:
  application:
    name: hzxc-service-cms-manager-client
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: bwqc_cms

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
bwqc:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    routingKey: 5d3c14370dc4d1328bef35b8 #此routingKey为门户站点ID5d3c14370dc4d1328bef35b8，5a751fab6abb5044e0d19ea1