
server:
  port: ${PORT:50101}   #服务端口
spring:
  application:
    name: eureka-server #服务名
eureka:
  client:
    service-url: #Eureka 客户端 与Eureka 服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己(不配置默认本机8761端口)
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/}
    fetch-registry: true #服务发现 是否从eureka 中获取注册信息
    register-with-eureka: true #服务注册 是否将自己注册到Eureka中
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01}